POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF5YXNlY2hpaGF5YSIsImlkIjoiNWVhYjVkZTU0ZmUxMzEyOWIwOWM2MjRjIiwiaWF0IjoxNTg4MjkyODcxfQ.9WpFZVQXPaWVITxpPDL4WlYxCSBw6b7Fd3bvm_vJhkg

{
    "content": "This note was written by Chihaya 3",
    "important": true
}